package g.a.a.z3;

import g.a.a.v;
import org.android.agoo.common.AgooConstants;
import org.android.agoo.message.MessageService;

/* JADX INFO: loaded from: classes2.dex */
public interface k {
    public static final v B4;
    public static final v C4;
    public static final v D4;
    public static final v E4;
    public static final v F4;
    public static final v G4;
    public static final v H4;
    public static final v I4;
    public static final v J4;
    public static final v K4;
    public static final v L4;
    public static final v M4;
    public static final v N4;
    public static final v O4;
    public static final v P4;
    public static final v Q4;
    public static final v R4;
    public static final v S4;
    public static final v T4;
    public static final v U3;
    public static final v U4;
    public static final v V3;
    public static final v V4;
    public static final v W3;
    public static final v W4;
    public static final v X3;
    public static final v X4;
    public static final v Y3;
    public static final v Y4;
    public static final v Z3;
    public static final v Z4;
    public static final v a4;
    public static final v a5;
    public static final v b4;
    public static final v b5;
    public static final v c4;
    public static final v c5;
    public static final v d4;
    public static final v d5;
    public static final v e4;
    public static final v e5;
    public static final v f4;
    public static final v f5;
    public static final v g4;
    public static final v g5;
    public static final v h4;
    public static final v h5;
    public static final v i4;
    public static final v i5;
    public static final v j4;
    public static final v j5;
    public static final v k4;
    public static final v l4;
    public static final v m4;
    public static final v n4;
    public static final v o4;
    public static final v p4;
    public static final v q4;
    public static final v r4;
    public static final v s4;
    public static final v t4;
    public static final v u4;
    public static final v v4;
    public static final v w4;
    public static final v x4;
    public static final v y4;
    public static final v z4;

    static {
        v vVar = new v("1.2.840.10045");
        U3 = vVar;
        v vVarBranch = vVar.branch("1");
        V3 = vVarBranch;
        W3 = vVarBranch.branch("1");
        v vVarBranch2 = vVarBranch.branch("2");
        X3 = vVarBranch2;
        Y3 = vVarBranch2.branch("3.1");
        Z3 = vVarBranch2.branch("3.2");
        a4 = vVarBranch2.branch("3.3");
        v vVarBranch3 = vVar.branch(MessageService.MSG_ACCS_READY_REPORT);
        b4 = vVarBranch3;
        c4 = vVarBranch3.branch("1");
        v vVarBranch4 = vVar.branch("2");
        d4 = vVarBranch4;
        e4 = vVarBranch4.branch("1");
        v vVarBranch5 = vVarBranch3.branch("3");
        f4 = vVarBranch5;
        g4 = vVarBranch5.branch("1");
        h4 = vVarBranch5.branch("2");
        i4 = vVarBranch5.branch("3");
        j4 = vVarBranch5.branch(MessageService.MSG_ACCS_READY_REPORT);
        v vVarBranch6 = vVar.branch("3");
        k4 = vVarBranch6;
        v vVarBranch7 = vVarBranch6.branch("0");
        l4 = vVarBranch7;
        m4 = vVarBranch7.branch("1");
        n4 = vVarBranch7.branch("2");
        o4 = vVarBranch7.branch("3");
        p4 = vVarBranch7.branch(MessageService.MSG_ACCS_READY_REPORT);
        q4 = vVarBranch7.branch("5");
        r4 = vVarBranch7.branch("6");
        s4 = vVarBranch7.branch("7");
        t4 = vVarBranch7.branch(MessageService.MSG_ACCS_NOTIFY_CLICK);
        u4 = vVarBranch7.branch(MessageService.MSG_ACCS_NOTIFY_DISMISS);
        v4 = vVarBranch7.branch(AgooConstants.ACK_REMOVE_PACKAGE);
        w4 = vVarBranch7.branch(AgooConstants.ACK_BODY_NULL);
        x4 = vVarBranch7.branch(AgooConstants.ACK_PACK_NULL);
        y4 = vVarBranch7.branch(AgooConstants.ACK_FLAG_NULL);
        z4 = vVarBranch7.branch(AgooConstants.ACK_PACK_NOBIND);
        B4 = vVarBranch7.branch(AgooConstants.ACK_PACK_ERROR);
        C4 = vVarBranch7.branch("16");
        D4 = vVarBranch7.branch("17");
        E4 = vVarBranch7.branch("18");
        F4 = vVarBranch7.branch("19");
        G4 = vVarBranch7.branch("20");
        v vVarBranch8 = vVarBranch6.branch("1");
        H4 = vVarBranch8;
        I4 = vVarBranch8.branch("1");
        J4 = vVarBranch8.branch("2");
        K4 = vVarBranch8.branch("3");
        L4 = vVarBranch8.branch(MessageService.MSG_ACCS_READY_REPORT);
        M4 = vVarBranch8.branch("5");
        N4 = vVarBranch8.branch("6");
        O4 = vVarBranch8.branch("7");
        P4 = new v("1.2.840.10040.4.1");
        Q4 = new v("1.2.840.10040.4.3");
        v vVar2 = new v("1.3.133.16.840.63.0");
        R4 = vVar2;
        S4 = vVar2.branch("2");
        T4 = vVar2.branch("3");
        U4 = vVar2.branch("16");
        v vVar3 = new v("1.2.840.10046");
        V4 = vVar3;
        W4 = vVar3.branch("2.1");
        v vVarBranch9 = vVar3.branch("3");
        X4 = vVarBranch9;
        Y4 = vVarBranch9.branch("1");
        Z4 = vVarBranch9.branch("2");
        a5 = vVarBranch9.branch("3");
        b5 = vVarBranch9.branch(MessageService.MSG_ACCS_READY_REPORT);
        c5 = vVarBranch9.branch("5");
        d5 = vVarBranch9.branch("6");
        e5 = vVarBranch9.branch("7");
        f5 = vVarBranch9.branch(MessageService.MSG_ACCS_NOTIFY_CLICK);
        v vVar4 = new v("1.3.133.16.840.9.44");
        g5 = vVar4;
        v vVarBranch10 = vVar4.branch("1");
        h5 = vVarBranch10;
        i5 = vVarBranch10.branch("1");
        j5 = vVarBranch10.branch("2");
    }
}
