package g.a.a.t3;

import g.a.a.v;
import org.android.agoo.common.AgooConstants;
import org.android.agoo.message.MessageService;

/* JADX INFO: loaded from: classes2.dex */
public interface a {
    public static final v B0;
    public static final v B1;
    public static final v B2;
    public static final v C2;
    public static final v D0;
    public static final v D1;
    public static final v D2;
    public static final v E0;
    public static final v E1;
    public static final v E2;
    public static final v F0;
    public static final v F1;
    public static final v F2;
    public static final v G0;
    public static final v G1;
    public static final v G2;
    public static final v H0;
    public static final v H1;
    public static final v H2;
    public static final v I0;
    public static final v I1;
    public static final v I2;
    public static final v J0;
    public static final v J1;
    public static final v J2;
    public static final v K0;
    public static final v K1;
    public static final v K2;
    public static final v L0;
    public static final v L1;
    public static final v L2;
    public static final v M0;
    public static final v M1;
    public static final v M2;
    public static final v N0;
    public static final v N1;
    public static final v N2;
    public static final v O0;
    public static final v O1;
    public static final v O2;
    public static final v P0;
    public static final v P1;
    public static final v P2;
    public static final v Q0;
    public static final v Q1;
    public static final v Q2;
    public static final v R0;
    public static final v R1;
    public static final v R2;
    public static final v S0;
    public static final v S1;
    public static final v S2;
    public static final v T0;
    public static final v T1;
    public static final v T2;
    public static final v U0;
    public static final v U1;
    public static final v U2;
    public static final v V0;
    public static final v V1;
    public static final v V2;
    public static final v W0;
    public static final v W1;
    public static final v X0;
    public static final v X1;
    public static final v X2;
    public static final v Y0;
    public static final v Y1;
    public static final v Y2;
    public static final v Z0;
    public static final v Z1;
    public static final v Z2;
    public static final v a1;
    public static final v a2;
    public static final v a3;
    public static final v b1;
    public static final v b2;
    public static final v b3;
    public static final v c2;
    public static final v c3;
    public static final v d1;
    public static final v d2;
    public static final v d3;
    public static final v e1;
    public static final v e2;
    public static final v e3;
    public static final v f1;
    public static final v f2;
    public static final v f3;
    public static final v g1;
    public static final v g2;
    public static final v g3;
    public static final v h1;
    public static final v h2;
    public static final v h3;
    public static final v i1;
    public static final v i2;
    public static final v i3;
    public static final v j1;
    public static final v j2;
    public static final v j3;
    public static final v k1;
    public static final v k2;
    public static final v k3;
    public static final v l1;
    public static final v l2;
    public static final v l3;
    public static final v m1;
    public static final v m2;
    public static final v m3;
    public static final v n1;
    public static final v n2;
    public static final v n3;
    public static final v o1;
    public static final v o2;
    public static final v o3;
    public static final v p1;
    public static final v p2;
    public static final v p3;
    public static final v q1;
    public static final v q2;
    public static final v q3;
    public static final v r0;
    public static final v r1;
    public static final v r2;
    public static final v r3;
    public static final v s0;
    public static final v s1;
    public static final v s2;
    public static final v s3;
    public static final v t0;
    public static final v t1;
    public static final v t2;
    public static final v t3;
    public static final v u0;
    public static final v u1;
    public static final v u2;
    public static final v v0;
    public static final v v1;
    public static final v v2;
    public static final v w0;
    public static final v w1;
    public static final v w2;
    public static final v x0;
    public static final v x1;
    public static final v x2;
    public static final v y0;
    public static final v y1;
    public static final v y2;
    public static final v z0;
    public static final v z1;
    public static final v z2;

    static {
        v vVar = new v("1.2.840.113549.1.1");
        r0 = vVar;
        s0 = vVar.branch("1");
        t0 = vVar.branch("2");
        u0 = vVar.branch("3");
        v0 = vVar.branch(MessageService.MSG_ACCS_READY_REPORT);
        w0 = vVar.branch("5");
        x0 = vVar.branch("6");
        y0 = vVar.branch("7");
        z0 = vVar.branch(MessageService.MSG_ACCS_NOTIFY_CLICK);
        B0 = vVar.branch(MessageService.MSG_ACCS_NOTIFY_DISMISS);
        D0 = vVar.branch(AgooConstants.ACK_REMOVE_PACKAGE);
        E0 = vVar.branch(AgooConstants.ACK_BODY_NULL);
        F0 = vVar.branch(AgooConstants.ACK_PACK_NULL);
        G0 = vVar.branch(AgooConstants.ACK_FLAG_NULL);
        H0 = vVar.branch(AgooConstants.ACK_PACK_NOBIND);
        I0 = vVar.branch(AgooConstants.ACK_PACK_ERROR);
        J0 = vVar.branch("16");
        v vVar2 = new v("1.2.840.113549.1.3");
        K0 = vVar2;
        L0 = vVar2.branch("1");
        v vVar3 = new v("1.2.840.113549.1.5");
        M0 = vVar3;
        N0 = vVar3.branch("1");
        O0 = vVar3.branch(MessageService.MSG_ACCS_READY_REPORT);
        P0 = vVar3.branch("3");
        Q0 = vVar3.branch("6");
        R0 = vVar3.branch(AgooConstants.ACK_REMOVE_PACKAGE);
        S0 = vVar3.branch(AgooConstants.ACK_BODY_NULL);
        T0 = vVar3.branch(AgooConstants.ACK_FLAG_NULL);
        U0 = vVar3.branch(AgooConstants.ACK_PACK_NULL);
        v vVar4 = new v("1.2.840.113549.3");
        V0 = vVar4;
        W0 = vVar4.branch("7");
        X0 = vVar4.branch("2");
        Y0 = vVar4.branch(MessageService.MSG_ACCS_READY_REPORT);
        v vVar5 = new v("1.2.840.113549.2");
        Z0 = vVar5;
        a1 = vVar5.branch("2");
        b1 = vVar5.branch(MessageService.MSG_ACCS_READY_REPORT);
        d1 = vVar5.branch("5");
        e1 = vVar5.branch("7").intern();
        f1 = vVar5.branch(MessageService.MSG_ACCS_NOTIFY_CLICK).intern();
        g1 = vVar5.branch(MessageService.MSG_ACCS_NOTIFY_DISMISS).intern();
        h1 = vVar5.branch(AgooConstants.ACK_REMOVE_PACKAGE).intern();
        i1 = vVar5.branch(AgooConstants.ACK_BODY_NULL).intern();
        j1 = vVar5.branch(AgooConstants.ACK_PACK_NULL).intern();
        k1 = vVar5.branch(AgooConstants.ACK_FLAG_NULL).intern();
        l1 = new v("1.2.840.113549.1.7").intern();
        m1 = new v("1.2.840.113549.1.7.1").intern();
        n1 = new v("1.2.840.113549.1.7.2").intern();
        o1 = new v("1.2.840.113549.1.7.3").intern();
        p1 = new v("1.2.840.113549.1.7.4").intern();
        q1 = new v("1.2.840.113549.1.7.5").intern();
        r1 = new v("1.2.840.113549.1.7.6").intern();
        v vVar6 = new v("1.2.840.113549.1.9");
        s1 = vVar6;
        t1 = vVar6.branch("1").intern();
        u1 = vVar6.branch("2").intern();
        v1 = vVar6.branch("3").intern();
        w1 = vVar6.branch(MessageService.MSG_ACCS_READY_REPORT).intern();
        x1 = vVar6.branch("5").intern();
        y1 = vVar6.branch("6").intern();
        z1 = vVar6.branch("7").intern();
        B1 = vVar6.branch(MessageService.MSG_ACCS_NOTIFY_CLICK).intern();
        D1 = vVar6.branch(MessageService.MSG_ACCS_NOTIFY_DISMISS).intern();
        E1 = vVar6.branch(AgooConstants.ACK_FLAG_NULL).intern();
        F1 = vVar6.branch(AgooConstants.ACK_PACK_NOBIND).intern();
        G1 = vVar6.branch(AgooConstants.ACK_PACK_ERROR).intern();
        v vVarIntern = vVar6.branch("16").intern();
        H1 = vVarIntern;
        I1 = vVar6.branch("16.2.46").intern();
        J1 = vVar6.branch("20").intern();
        K1 = vVar6.branch(AgooConstants.REPORT_MESSAGE_NULL).intern();
        L1 = vVar6.branch("22.1");
        v vVarBranch = vVar6.branch(AgooConstants.REPORT_ENCRYPT_FAIL);
        M1 = vVarBranch;
        N1 = vVarBranch.branch("1").intern();
        O1 = vVarBranch.branch("2").intern();
        v vVarBranch2 = vVar6.branch(AgooConstants.REPORT_DUPLICATE_FAIL);
        P1 = vVarBranch2;
        Q1 = vVarBranch2.branch("1").intern();
        R1 = vVar6.branch("52").intern();
        S1 = vVar6.branch("15.1");
        T1 = vVar6.branch("15.2");
        U1 = vVar6.branch("15.3");
        v vVar7 = new v("1.2.840.113549.1.9.16.1");
        V1 = vVar7;
        W1 = vVar7.branch("2");
        X1 = vVar7.branch(MessageService.MSG_ACCS_READY_REPORT);
        Y1 = vVar7.branch(MessageService.MSG_ACCS_NOTIFY_DISMISS);
        Z1 = vVar7.branch(AgooConstants.REPORT_DUPLICATE_FAIL);
        a2 = vVar7.branch("31");
        v vVarBranch3 = vVarIntern.branch("3");
        b2 = vVarBranch3;
        c2 = vVarBranch3.branch(MessageService.MSG_ACCS_NOTIFY_DISMISS);
        d2 = vVarBranch3.branch(AgooConstants.ACK_PACK_NOBIND);
        e2 = vVarBranch3.branch("17");
        f2 = vVarBranch3.branch("18");
        g2 = vVarBranch3.branch("28");
        h2 = vVarBranch3.branch("29");
        i2 = vVarBranch3.branch("30");
        v vVar8 = new v("1.2.840.113549.1.9.16.6");
        j2 = vVar8;
        k2 = vVar8.branch("1");
        l2 = vVar8.branch("2");
        m2 = vVar8.branch("3");
        n2 = vVar8.branch(MessageService.MSG_ACCS_READY_REPORT);
        o2 = vVar8.branch("5");
        p2 = vVar8.branch("6");
        v vVar9 = new v("1.2.840.113549.1.9.16.2");
        q2 = vVar9;
        r2 = vVar9.branch("1");
        s2 = vVar9.branch(MessageService.MSG_ACCS_READY_REPORT);
        t2 = vVar9.branch("5");
        u2 = vVar9.branch(AgooConstants.ACK_REMOVE_PACKAGE);
        v2 = vVar9.branch(AgooConstants.ACK_BODY_NULL);
        w2 = vVar9.branch(AgooConstants.ACK_PACK_NULL);
        x2 = vVar9.branch("47");
        y2 = vVar9.branch("7");
        z2 = vVar9.branch(AgooConstants.ACK_PACK_NOBIND);
        v vVarBranch4 = vVar9.branch(AgooConstants.ACK_PACK_ERROR);
        B2 = vVarBranch4;
        v vVarBranch5 = vVar9.branch("16");
        C2 = vVarBranch5;
        v vVarBranch6 = vVar9.branch("17");
        D2 = vVarBranch6;
        E2 = vVar9.branch("18");
        v vVarBranch7 = vVar9.branch("19");
        F2 = vVarBranch7;
        G2 = vVar9.branch("20");
        H2 = vVar9.branch(AgooConstants.REPORT_MESSAGE_NULL);
        I2 = vVar9.branch(AgooConstants.REPORT_ENCRYPT_FAIL);
        J2 = vVar9.branch(AgooConstants.REPORT_DUPLICATE_FAIL);
        K2 = vVar9.branch(AgooConstants.REPORT_NOT_ENCRYPT);
        L2 = vVar9.branch("25");
        M2 = vVar9.branch("26");
        N2 = vVar9.branch("27");
        O2 = vVar9.branch("37");
        P2 = vVar9.branch("38");
        Q2 = vVar9.branch("54");
        R2 = vVar9.branch("43");
        S2 = vVar9.branch("40");
        T2 = vVarBranch4;
        U2 = vVarBranch5;
        V2 = vVarBranch6;
        X2 = vVarBranch7;
        Y2 = new v("1.2.840.113549.1.9.16.5.1");
        Z2 = new v("1.2.840.113549.1.9.16.5.2");
        v vVar10 = new v("1.2.840.113549.1.12");
        a3 = vVar10;
        v vVarBranch8 = vVar10.branch("10.1");
        b3 = vVarBranch8;
        c3 = vVarBranch8.branch("1");
        d3 = vVarBranch8.branch("2");
        e3 = vVarBranch8.branch("3");
        f3 = vVarBranch8.branch(MessageService.MSG_ACCS_READY_REPORT);
        g3 = vVarBranch8.branch("5");
        h3 = vVarBranch8.branch("6");
        v vVarBranch9 = vVar10.branch("1");
        i3 = vVarBranch9;
        j3 = vVarBranch9.branch("1");
        k3 = vVarBranch9.branch("2");
        l3 = vVarBranch9.branch("3");
        m3 = vVarBranch9.branch(MessageService.MSG_ACCS_READY_REPORT);
        n3 = vVarBranch9.branch("5");
        o3 = vVarBranch9.branch("6");
        p3 = vVarBranch9.branch("6");
        q3 = new v("1.2.840.113549.1.9.16.3.6");
        r3 = new v("1.2.840.113549.1.9.16.3.7");
        s3 = new v("1.2.840.113549.1.9.16.3.5");
        t3 = new v("1.2.840.113549.1.9.16.3.10");
    }
}
